#!/usr/bin/env bash
# A Bash script that pings an IP address passed as an argument.

# Check if no arguments are passed
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Check if more than one argument is passed
if [ $# -gt 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$1"
