#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and handles SIGTERM signal

trap 'echo "I am invincible!!!"; exit 0' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
