#!/usr/bin/env bash

pid_file="/var/run/my_process.pid"
logfile="/tmp/my_process"

start_process() {
    echo $$ > "$pid_file"
    echo "manage_my_process started"
    while true; do
        echo "I am alive!" >> "$logfile"
        sleep 2
    done
}

stop_process() {
    if [ -f "$pid_file" ]; then
        pid=$(cat "$pid_file")
        kill "$pid"
        rm -f "$pid_file"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart_process() {
    stop_process
    start_process &
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process &
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
