#!/usr/bin/env bash

# Read /etc/passwd using while loop and IFS to display user information
while IFS=":" read -r username _ userid groupid info home shell; do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd
