#!/usr/bin/env bash
# This script displays the content of the current directory, showing only part of the name after the first dash

for file in *
do
  if [[ "$file" == *-* ]]; then
    echo "${file#*-}"
  fi
done
