#!/usr/bin/env bash
# This script configures localhost to resolve to 127.0.0.2 and facebook.com to resolve to 8.8.8.8

# Modify localhost resolution
sudo sed -i '1 s/^.*$/127.0.0.2 localhost/' /etc/hosts

# Modify facebook.com resolution
sudo sed -i 's/^.*facebook.com$/8.8.8.8 facebook.com/' /etc/hosts
